players_info = {
    'Marcus Rashford': {'Position': 'Forward', 'Shooting accuracy': '53%', 'Passing accuracy': '80%', 'Appearances': '42', 'image_path': './images/rashford.png'},
    'Marcus Martial': {'Position': 'Forward', 'Shooting accuracy': '83%', 'Passing accuracy': '80%', 'Appearances': '19', 'image_path': './images/martial.png'},
    'Alejandro Garnacho': {'Position': 'Forward', 'Shooting accuracy': '49%', 'Passing accuracy': '81%', 'Appearances': '49', 'image_path': './images/garnacho.png'},
    'Rasmus Hojlund': {'Position': 'Forward', 'Shooting accuracy': '64%', 'Passing accuracy': '76%', 'Appearances': '42', 'image_path': './images/hojlund.png'},
    'Bruno Fernandes': {'Position': 'Midfielder', 'Shooting accuracy': '55%', 'Passing accuracy': '79%', 'Appearances': '47', 'image_path': './images/fernandes.png'},
    'Mason Mount': {'Position': 'Midfielder', 'Shooting accuracy': '43%', 'Passing accuracy': '85%', 'Appearances': '19', 'image_path': './images/mount.png'},
    'Christian Eriksen': {'Position': 'Midfielder', 'Shooting accuracy': '60%', 'Passing accuracy': '83%', 'Appearances': '28', 'image_path': './images/eriksen.png'},
    'Diogo Dalot': {'Position': 'Defender', 'Shooting accuracy': '39%', 'Passing accuracy': '84%', 'Appearances': '49', 'image_path': './images/dalot.png'},
    'Harry Maguire': {'Position': 'Defender', 'Shooting accuracy': '38%', 'Passing accuracy': '84%', 'Appearances': '31', 'image_path': './images/maguire.png'},
    'Victor Lindelof': {'Position': 'Defender', 'Shooting accuracy': '63%', 'Passing accuracy': '89%', 'Appearances': '27', 'image_path': './images/lindelof.png'},
    'Melvine Malard': {'Position': 'Forward', 'Shooting accuracy': '46%', 'Passing accuracy': '74%', 'Appearances': '19', 'image_path': './images/malard.png'},
    'Lucia Garcia': {'Position': 'Forward', 'Shooting accuracy': '46%', 'Passing accuracy': '74%', 'Appearances': '19', 'image_path': './images/garcia.png'},
    'Nikita Parris': {'Position': 'Forward', 'Shooting accuracy': '49%', 'Passing accuracy': '76%', 'Appearances': '21', 'image_path': './images/parris.png'},
    'Ella Toone': {'Position': 'Midfielder', 'Shooting accuracy': '36%', 'Passing accuracy': '77%', 'Appearances': '22', 'image_path': './images/toone.png'},
    'Irene Guerrero': {'Position': 'Midfielder', 'Shooting accuracy': '100%', 'Passing accuracy': '65%', 'Appearances': '3', 'image_path': './images/guerrero.png'},
    'Katie Zelem': {'Position': 'Midfielder', 'Shooting accuracy': '29%', 'Passing accuracy': '76%', 'Appearances': '22', 'image_path': './images/zelem.png'},
    'Gabby George': {'Position': 'Defender', 'Shooting accuracy': '0%', 'Passing accuracy': '76%', 'Appearances': '3', 'image_path': './images/george.png'},
    'Hannah Blundell': {'Position': 'Defender', 'Shooting accuracy': '42%', 'Passing accuracy': '85%', 'Appearances': '22', 'image_path': './images/blundell.png'},
    'Jayde Riviere': {'Position': 'Defender', 'Shooting accuracy': '50%', 'Passing accuracy': '76%', 'Appearances': '15', 'image_path': './images/riviere.png'},

}