players_info = {
    'Erling Haaland': {'Position': 'Forward', 'Shooting accuracy': '51%', 'Tackles': '11', 'Appearances': '71', 'image_path': './images/haland.png'},
    'Mohamed Salah': {'Position': 'Forward', 'Shooting accuracy': '44%', 'Tackles': '131', 'Appearances': '268', 'image_path': './images/Salah.png'},
    'Luis Díaz': {'Position': 'Forward', 'Shooting accuracy': '35%', 'Tackles': '68', 'Appearances': '72', 'image_path': './images/luis.png'},
    'Phil Foden': {'Position': 'Midfielder', 'Shooting accuracy': '44%', 'Tackles': '107', 'Appearances': '166', 'image_path': './images/foden.png'},
    'Rasmus Hojlund': {'Position': 'Forward', 'Shooting accuracy': '55%', 'Tackles': '11', 'Appearances': '31', 'image_path': './images/hojlund.png'},
    'Bukayo Saka': {'Position': 'Forward', 'Shooting accuracy': '35%', 'Tackles': '239', 'Appearances': '175', 'image_path': './images/saka.png'},
    'Bruno Fernandes': {'Position': 'Midfielder', 'Shooting accuracy': '39%', 'Tackles': '284', 'Appearances': '164', 'image_path': './images/fernandes.png'},
    'Marcus Rashford': {'Position': 'Forward', 'Shooting accuracy': '53%', 'Tackles': '139', 'Appearances': '43', 'image_path': './images/rashford.png'},
    'Bruno Guimarães': {'Position': 'Midfielder', 'Shooting accuracy': '37%', 'Tackles': '223', 'Appearances': '91', 'image_path': './images/bruno.png'},
    'William Saliba': {'Position': 'Defender', 'Shooting accuracy': '38%', 'Tackles': '93', 'Appearances': '70', 'image_path': './images/saliba.png'},
    'Melvine Malard': {'Position': 'Forward', 'Shooting accuracy': '46%', 'Tackles': '51', 'Appearances': '19', 'image_path': './images/malard.png'},
    'Lucia Garcia': {'Position': 'Forward', 'Shooting accuracy': '46%', 'Tackles': '47', 'Appearances': '19', 'image_path': './images/garcia.png'},
    'Nikita Parris': {'Position': 'Forward', 'Shooting accuracy': '49%', 'Tackles': '76', 'Appearances': '21', 'image_path': './images/parris.png'},
    'Ella Toone': {'Position': 'Midfielder', 'Shooting accuracy': '36%', 'Tackles': '77', 'Appearances': '22', 'image_path': './images/toone.png'},
    'Irene Guerrero': {'Position': 'Midfielder', 'Shooting accuracy': '100%', 'Tackles': '65', 'Appearances': '3', 'image_path': './images/guerrero.png'},
    'Katie Zelem': {'Position': 'Midfielder', 'Shooting accuracy': '29%', 'Tackles': '76', 'Appearances': '22', 'image_path': './images/zelem.png'},
    'Gabby George': {'Position': 'Defender', 'Shooting accuracy': '0%', 'Tackles': '76', 'Appearances': '3', 'image_path': './images/george.png'},
    'Hannah Blundell': {'Position': 'Defender', 'Shooting accuracy': '42%', 'Tackles': '85', 'Appearances': '22', 'image_path': './images/blundell.png'},
    'Jayde Riviere': {'Position': 'Defender', 'Shooting accuracy': '50%', 'Tackles': '76', 'Appearances': '15', 'image_path': './images/riviere.png'},
}
